### ISSUE TITLE
Unable to Authorize 

### ISSUE THREAD

**Issue by MattGHarvey** [jeremybrooks/SuprSetr#12] opened 2019-11-26 04:07 UTC
Windows 10:
Clicking the "Authorize" button gives "There was an error while attempting to authorize." message.

**Comment by jeremybrooks** [comment] 2019-11-26 20:10
Thanks for the report. This duplicates issue #9. The root cause is in the library used to perform OAuth requests in the underlying flickr library (jinx). I'm in the process of fixing jinx, then will update suprsetr to use the newer stuff.

**Comment by MattGHarvey** [comment] 2020-02-03 13:49
Any updates on this?

**Comment by jeremybrooks** [comment] 2020-02-03 17:52
I have the library working for auth and for GET requests, working on making POST requests work. The way requests are signed changed pretty drastically in the scribe library (which is what I'm using to handle OAuth).

**Comment by MattGHarvey** [comment] 2020-02-03 18:15
Awesome...looking forward to the new version...I have a bunch of albums that need updating!

**Comment by jeremybrooks** [comment] 2020-03-24 04:55
Fixed in version 3.0.0. Available via maven.

**Closed as completed by jeremybrooks** 2020-03-24 04:55 UTC

**Comment by jeremybrooks** [comment] 2020-03-24 04:57
That is, fixed in version 3.0.0 of Jinx; SuprSetr version 3.4.0 is available with the fixed library.
